language: node_js

node_js:
  - '10'

services:
  - mongodb

install:
  - npm install

before_script:
  - sleep 15
  
script:
  - npm run lint
  - npm run test
  
cache:
  directories:
    - node_modules

branches:
  only: 
    - master